---
  - name: Check if Java is already installed
    stat:
      path: "{{ jdk_path }}"
    register: folder

  - name: Install OpenJDK
    yum: name=java-1.8.0-openjdk-devel.x86_64 state=present    
    when: not folder.stat.exists

