---
  - name: Set Java, Hadoop, and Zookeper Env variables
    blockinfile:
     path: ~/.bashrc
     block: |

          export HDFS_NAMENODE_USER="root"
          export HDFS_DATANODE_USER="root"
          export YARN_RESOURCEMANAGER_USER="root"
          export YARN_NODEMANAGER_USER="root"
          export HDFS_JOURNALNODE_USER="root"
          export HDFS_ZKFC_USER="root"

          export HADOOP_HOME=$HOME/hadoop-{{ hadoop_version }}
          export HADOOP_MAPRED_HOME=$HADOOP_HOME
          export HADOOP_COMMON_HOME=$HADOOP_HOME
          export HADOOP_HDFS_HOME=$HADOOP_HOME
          export YARN_HOME=$HADOOP_HOME
          export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
          export YARN_CONF_DIR=$HADOOP_HOME/etc/hadoop
          export ZOOKEEPER_HOME=$HOME/zookeeper-{{ zkversion }}
          export JAVA_HOME={{ jdk_path }}
          export PATH=$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$ZOOKEEPER_HOME/bin


          export HADOOP_OPTS="$HADOOP_OPTS -Djava.library.path=$HADOOP_HOME/lib/native"
          export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"

