---
  - name: Copy the Zookeeper file
    copy: 
      src: "{{ zk_path }}/conf/zoo_sample.cfg"
      dest: "{{ zk_path }}/conf/zoo.cfg"

  - name: Configure the ZK config file
    blockinfile:      
      path: "{{ zk_path }}/conf/zoo.cfg"
      block: |
        dataDir: {{ zk_data_dir }}
        
        {% for host in groups['cluster01'] %}
        Server.{{ loop.index }}={{ host }}:2888:3888
        {% endfor %}

      
